{
  "_from": "axios-error@^1.0.0-beta.5",
  "_id": "axios-error@1.0.0-beta.5",
  "_inBundle": false,
  "_integrity": "sha512-4am9f3iw64uNUluPkSBGiNmCbtC8sRk8Yy0VztlvzF/WcA4RKWDW1OkAYOoHCvDa2/KNPMHPd2/kCoQxRCIl1g==",
  "_location": "/axios-error",
  "_phantomChildren": {},
  "_requested": {
    "type": "range",
    "registry": true,
    "raw": "axios-error@^1.0.0-beta.5",
    "name": "axios-error",
    "escapedName": "axios-error",
    "rawSpec": "^1.0.0-beta.5",
    "saveSpec": null,
    "fetchSpec": "^1.0.0-beta.5"
  },
  "_requiredBy": [
    "/messaging-api-line",
    "/messaging-api-messenger",
    "/messaging-api-slack",
    "/messaging-api-telegram",
    "/messaging-api-viber"
  ],
  "_resolved": "https://registry.npmjs.org/axios-error/-/axios-error-1.0.0-beta.5.tgz",
  "_shasum": "4628b91d89a25bde810f4c388f456b23274868f9",
  "_spec": "axios-error@^1.0.0-beta.5",
  "_where": "/Users/fij/www/bottender-chatbot/node_modules/messaging-api-line",
  "bugs": {
    "url": "https://github.com/Yoctol/messaging-apis/issues"
  },
  "bundleDependencies": false,
  "deprecated": false,
  "description": "An axios error wrapper that aim to provide clear error message to the user",
  "devDependencies": {
    "axios": "^0.19.0",
    "axios-mock-adapter": "^1.17.0"
  },
  "engines": {
    "node": ">=8"
  },
  "gitHead": "701efe776414a93d93d709198a72fc80991f51fc",
  "homepage": "https://github.com/Yoctol/messaging-apis#readme",
  "keywords": [
    "axios",
    "error",
    "http"
  ],
  "license": "MIT",
  "main": "dist/index.js",
  "name": "axios-error",
  "repository": {
    "type": "git",
    "url": "git+https://github.com/Yoctol/messaging-apis.git"
  },
  "types": "dist/index.d.ts",
  "version": "1.0.0-beta.5"
}
